# Generated by Django 4.2.11 on 2026-04-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subject_name',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
