# Generated by Django 4.2.11 on 2026-04-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
