# Generated by Django 4.2.11 on 2026-05-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_permissions_json'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'department', 'stage')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='is_retake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='subject_name',
        ),
    ]
