# Generated by Django 4.2.11 on 2026-04-22 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='retake_students',
            field=models.ManyToManyField(blank=True, related_name='retake_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExamCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('stage', models.IntegerField()),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='seating.examsession')),
            ],
        ),
    ]
