# Generated by Django 4.2.11 on 2026-04-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0002_alter_examsession_retake_students_examcohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcohort',
            name='subject_name',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
