# Generated by Django 4.2.11 on 2026-04-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0003_examcohort_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='pos_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seat',
            name='pos_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
