# Generated by Django 4.2.11 on 2026-04-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0004_seat_pos_x_seat_pos_y_alter_examsession_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='time_range',
            field=models.CharField(default='9 to 11', max_length=50),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='title',
            field=models.CharField(blank=True, default='Room Mapping', max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together={('hall', 'time_range')},
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='start_time',
        ),
    ]
