# Generated by Django 4.2.11 on 2026-04-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0005_examsession_time_range_alter_examsession_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
