# Generated by Django 4.2.11 on 2026-04-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0006_seat_seat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='seating_grid',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
